// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETD3202_Lab5_V2.Models;

namespace NETD3202_Lab5_V2.Migrations
{
    [DbContext(typeof(VideoGameContext))]
    partial class VideoGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NETD3202_Lab5_V2.Models.MoreDetail", b =>
                {
                    b.Property<int>("gID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gID");

                    b.ToTable("MoreDetails");
                });

            modelBuilder.Entity("NETD3202_Lab5_V2.Models.VideoGame", b =>
                {
                    b.Property<int>("gameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("esrb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gameName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("releaseYear")
                        .HasColumnType("int");

                    b.HasKey("gameID");

                    b.ToTable("VideoGames");
                });

            modelBuilder.Entity("NETD3202_Lab5_V2.Models.MoreDetail", b =>
                {
                    b.HasOne("NETD3202_Lab5_V2.Models.VideoGame", "gameID")
                        .WithMany()
                        .HasForeignKey("gID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gameID");
                });
#pragma warning restore 612, 618
        }
    }
}
